/**
 * Bitmap piece-set manifests. Each manifest maps a `PieceType.internalName` to
 * one or two PNG URLs:
 *
 *  - `shared`: a single `light` URL; the BoardView inverts it for the dark side.
 *  - `per-side`: explicit `light` (white) and `dark` (black) URLs, rendered as-is.
 *
 * Generated by `pnpm convert-assets`.
 */

import standardSet from './assets/pieceSet-Standard.json' with { type: 'json' };
import abstractSet from './assets/pieceSet-Abstract.json' with { type: 'json' };
import smallSet from './assets/pieceSet-Small.json' with { type: 'json' };
import motifSet from './assets/pieceSet-Motif.json' with { type: 'json' };
import eurasianSet from './assets/pieceSet-Eurasian.json' with { type: 'json' };
import runesSet from './assets/pieceSet-Runes.json' with { type: 'json' };

/** A single piece image, possibly per side. */
export interface PieceImageEntry {
  /** URL of the white-side image (or the only image, in shared mode). */
  light: string;
  /** Optional explicit dark-side image; if absent, the BoardView inverts `light`. */
  dark?: string;
}

/** The shape of the JSON written by `tools/convert-assets.ts`. */
export interface PieceSetManifest {
  set: string;
  imageSize: number;
  /** Rendering mode — see module docstring. */
  mode: 'shared' | 'per-side';
  pieces: Record<string, PieceImageEntry>;
}

/** `null` means use Unicode glyphs (the always-present fallback). */
export const PIECE_SETS: Record<string, PieceSetManifest | null> = {
  Unicode: null,
  Standard: standardSet as PieceSetManifest,
  Abstract: abstractSet as PieceSetManifest,
  Small: smallSet as PieceSetManifest,
  Motif: motifSet as PieceSetManifest,
  Eurasian: eurasianSet as PieceSetManifest,
  Runes: runesSet as PieceSetManifest,
};

export const DEFAULT_PIECE_SET = 'Standard';
